DROP DATABASE IF EXISTS dinero_db;
CREATE DATABASE dinero_db;

USE dinero_db;

CREATE TABLE Dinero(
  ID INT AUTO_INCREMENT NOT NULL,
  transDate TIMESTAMP NOT NULL, 
  category VARCHAR (100) NOT NULL,
  creditDebit BOOLEAN DEFAULT FALSE,
  transAmount DECIMAL(10,2) NOT NULL, 
  PRIMARY KEY (id)
);

SELECT * FROM dinero;